@echo off
setlocal enabledelayedexpansion

echo =====================================================================
echo BAMBU BATCH IMAGE MOVE + LOGGING
echo =====================================================================

:: 1. Check if a master folder was dropped
if "%~1"=="" (
    echo [ERROR] Please drag and drop the MASTER FOLDER onto this script.
    pause
    exit /b
)

:: Strip trailing backslash if present - prevents broken log file paths
set "masterDir=%~1"
if "%masterDir:~-1%"=="\" set "masterDir=%masterDir:~0,-1%"
set "logFile=%masterDir%\ProcessLog.txt"

echo Processing started: %date% %time% > "%logFile%"
echo --------------------------------------------------------- >> "%logFile%"

:: 2. Recursively search for *Full.gcode.3mf files
for /r "%masterDir%" %%F in (*Full.gcode.3mf) do (
    set "targetFile=%%~fF"
    set "workingDir=%%~dpF"
    set "originalFullName=%%~nxF"

    :: Strip the separator + Full.gcode.3mf to get the bare model name.
    :: Handles both "Bat.Full.gcode.3mf" -> "Bat" and "Ghost_Full.gcode.3mf" -> "Ghost"
    set "strippedName=%%~nxF"
    set "strippedName=!strippedName:_Full.gcode.3mf=!"
    set "strippedName=!strippedName:.Full.gcode.3mf=!"

    :: Look specifically for the slicePreview generated by Python
    set "newPng="
    if exist "!workingDir!!strippedName!_slicePreview.png" (
        set "newPng=!workingDir!!strippedName!_slicePreview.png"
    )

    echo.
    echo ---------------------------------------------------------
    echo Folder: !workingDir!
    echo Base name: !strippedName!

    if not defined newPng (
        echo [SKIP] No PNG found for !originalFullName!
        echo [SKIP] No PNG found in: !workingDir! >> "%logFile%"
    ) else (
        echo [MOVING] !newPng!
        call :ProcessAndMove "!targetFile!" "!newPng!" "!workingDir!" "!originalFullName!"
        echo [SUCCESS] Processed !originalFullName! >> "%logFile%"
    )
)

echo.
echo --------------------------------------------------------- >> "%logFile%"
echo Processing finished: %date% %time% >> "%logFile%"
echo =====================================================================
echo All tasks complete! Log saved to: %logFile%
exit /b

:: ---------------------------------------------------------
:: Processing Subroutine
:: ---------------------------------------------------------
:ProcessAndMove
set "thisFile=%~1"
set "thisPng=%~2"
set "thisDir=%~3"
set "thisName=%~4"

:: Create unique local temp folder to avoid sync locks
set "localTemp=%TEMP%\BambuReplace_%RANDOM%"
mkdir "%localTemp%"

:: Rename to .zip to allow tar extraction
set "zipName=%thisName:.gcode.3mf=.zip%"
rename "%thisFile%" "%zipName%"
if errorlevel 1 (
    echo [ERROR] Could not rename %thisFile% - file may be locked by Synology Drive sync.
    rd /s /q "%localTemp%"
    exit /b
)

:: Extract to local %%TEMP%%
tar.exe -xf "%thisDir%%zipName%" -C "%localTemp%"
if errorlevel 1 (
    echo [ERROR] tar extraction failed for %thisDir%%zipName%
    rename "%thisDir%%zipName%" "%thisName%"
    rd /s /q "%localTemp%"
    exit /b
)

:: Find Metadata folder regardless of case
set "metadataDir="
for /f "delims=" %%D in ('dir /b /s /ad "%localTemp%" 2^>nul ^| findstr /i "\\Metadata$"') do (
    set "metadataDir=%%D"
)

if defined metadataDir (
    move /y "%thisPng%" "%metadataDir%\plate_1.png" >nul
    echo [OK] Replaced plate_1.png in: %metadataDir%
) else (
    echo [WARN] Metadata folder not found. Archive contents:
    dir /b /s "%localTemp%"
)

:: Re-zip and move back to original location
del "%thisDir%%zipName%"
pushd "%localTemp%"
tar.exe -a -cf "%thisDir%%zipName%" *
popd
if errorlevel 1 (
    echo [ERROR] tar re-compression failed.
    rd /s /q "%localTemp%"
    exit /b
)

:: Final Rename back to 3MF
rename "%thisDir%%zipName%" "%thisName%"
if errorlevel 1 (
    echo [ERROR] Could not rename back to %thisName%
)

:: Cleanup local buffer
rd /s /q "%localTemp%"
exit /b